#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

[build]
command = "curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm && pnpm install && pnpm run build"
